<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TicketTriageAgent.WorkerService-7ccbb5b7-06bc-4f88-9e69-f4f5aa5b07b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.2.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="RabbitMQ.Client" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.MessageBus\Shared.MessageBus.csproj" />
    <ProjectReference Include="..\WebApplication.ServiceDefaults\WebApplication.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
