services:
  deployfoundrycustomeragent:
    image: educationfoundry.azurecr.io/deployfoundrycustomeragent:v4
    build:
      context: .
      dockerfile: DeployFoundryCustomerAgent/Dockerfile

  deployfounderycustomeragentviaemptyproject:
    image: educationfoundry.azurecr.io/simpleagent:v1
    build:
      context: .
      dockerfile: DeployFounderyCustomerAgentViaEmptyProject/Dockerfile

