@WebApplicationAPI_HostAddress = http://localhost:5191

### Classify a positive comment
POST {{WebApplicationAPI_HostAddress}}/sentiment
Content-Type: application/json

{
  "comment": "Bu ürünü çok beğendim, harika bir deneyimdi."
}

### Classify a negative comment
POST {{WebApplicationAPI_HostAddress}}/sentiment
Content-Type: application/json

{
  "comment": "Çok kötü bir deneyimdi, hiç memnun kalmadım."
}

### Classify a neutral comment
POST {{WebApplicationAPI_HostAddress}}/sentiment
Content-Type: application/json

{
  "comment": "Ürün açıklandığı gibi geldi, standart bir deneyimdi."
}

###

