@DeployFoundryCustomerAgent_HostAddress = https://localhost:7041

### 1. Yeni sohbet başlat (conversationId göndermiyoruz)
POST {{DeployFoundryCustomerAgent_HostAddress}}/responses
Content-Type: application/json

{
  "input": "Kablosuz Kulaklık fiyatı nedir?"
}

###

### 2. Aynı oturumu devam ettir
### Yanıttaki "id" değerini conversationId olarak gönder
POST {{DeployFoundryCustomerAgent_HostAddress}}/responses
Content-Type: application/json

{
  "input": "biraz önce ne sordum?",
  "conversationId": "29e9f575-36a6-42b3-819a-76727b3ce55d"
}

###

### 3. Sağlık kontrolü
GET {{DeployFoundryCustomerAgent_HostAddress}}/readiness

###
